# Generated by Django 3.1.7 on 2021-09-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudaichatapp', '0005_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='fudaichatapp.question'),
        ),
    ]
